# Üldised määratlused
title: X-tee rakendusjuhend
baseurl: "/X-tee-rakendusjuhend"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
